local kut = require "config.keymap.utils"
local lsput = require "utils.lsp"
local winsize = require "config.keymap.winsize" (5)
local qfix = require "config.keymap.qfix"
local althelp = require "config.keymap.althelp".althelp
local M = {}

M.global = kut.newMapGroup()
    :map('n', "G", "Gzz", "Jump to line centers the screen on that line")
    :map('v', "<C-C>", [["*y :let @+=@*<CR>]], "ctrl-c to copy to clipboard")
    :map('n', "vv", "V", "vv to select whole line")
    :map('n', "V", "v$", "V to select until the end of the line")
    :map('n', "<A-y>", "zl", "Use alt-y to scroll right")
    :map('n', "<A-e>", "zh", "Use alt-e to scroll left")
    :map('t', "<C-[><C-[>", [[<C-\><C-n>]], "Double esc for normal mode in terminal")
    :map('n', "<A-l>", "gt", "alt-l for next tab")
    :map('n', "<A-h>", "gT", "alt-h for prev tab")
    :map({ 'i', 't' }, "<A-l>", [[<C-\><C-N>gt]], "alt-l for next tab in terminal and insert mode")
    :map({ 'i', 't' }, "<A-h>", [[<C-\><C-N>gT]], "alt-h for prev tab in terminal and insert mode")
    :map({ 'i', 't' }, "<C-h>", [[<C-\><C-N><C-w>h]], "Use ctrl-h to switch windows in insert and terminal modes")
    :map({ 'i', 't' }, "<C-j>", [[<C-\><C-N><C-w>j]], "Use ctrl-j to switch windows in insert and terminal modes")
    :map({ 'i', 't' }, "<C-k>", [[<C-\><C-N><C-w>k]], "Use ctrl-k to switch windows in insert and terminal modes")
    :map('i', "<C-l>", [[<C-\><C-N><C-w>l]], "use ctrl-l to switch windows in insert mode")
    :map('n', "<C-h>", "<C-w>h", "Use ctrl-h to switch windows in normal mode")
    :map('n', "<C-j>", "<C-w>j", "Use ctrl-j to switch windows in normal mode")
    :map('n', "<C-k>", "<C-w>k", "Use ctrl-k to switch windows in normal mode")
    :map('n', "<C-l>", "<C-w>l", "Use ctrl-l to switch windows in normal mode")
    :map('n', "<C-w>t", "<CMD>tab split<CR>", "CTRL-W_t behaves like CTRL-W_T but without closing the old window")
    :map('t', "<C-l>", "<space>clear<CR>", "Clear terminal screen")
    :map('n', "<C-A-h>", winsize.changeWindowSize("h"), "Resize window to the right")
    :map('n', "<C-A-j>", winsize.changeWindowSize("j"), "Resize window down")
    :map('n', "<C-A-k>", winsize.changeWindowSize("k"), "Resize window up")
    :map('n', "<C-A-l>", winsize.changeWindowSize("l"), "Resize window left")
    :map('n', "<A-j>", "<CMD>m +1<CR>", "Move line down")
    :map('n', "<A-k>", "<CMD>m -2<CR>", "Move line up")
    :map('v', "<A-j>", ":m '>+1<CR>gv", "Move lines down")
    :map('v', "<A-k>", ":m '<-2<CR>gv", "Move lines up")
    :map({ 'n', 'i', 'v' }, "<up>", "<nop>", "Dispable up arrow")
    :map({ 'n', 'i', 'v' }, "<down>", "<nop>", "Dispable down arrow")
    :map({ 'n', 'i', 'v' }, "<left>", "<nop>", "Dispable left arrow")
    :map({ 'n', 'i', 'v' }, "<right>", "<nop>", "Dispable right arrow")
    :map('n', "<leader>b", "<C-^>", "Leader-b to go to preavious file")
    :map('n', "<leader>tt", kut.todo("dk949"), "Insert a todo comment")
    :map('n', "<Leader>mt", "<CMD>split<Bar>term<CR>", "Start the terminal")
    :map('n', "<leader>mc", "<CMD>set cursorline!<CR>", "Highlight current line")
    :map('n', "<leader>nn", "<CMD>Oil --float<CR>", "Open Oil window")
    :map('n', "gqg", kut.formatFile, "format the whole file with standard formatting")
    :map('n', ']q', qfix.cnext, "next quickfix")
    :map('n', '[q', qfix.cprev, "previous quickfix")
    :map('n', "<leader><S-K>", althelp, "Man/help page for symbol under cursor")
    :map('i', "<C-space>", "<nop>", "disable ctrl-space in insert mode")


M.lsp = kut.newMapGroup()
    :map('n', "<leader>ch", lsput.toggleInlay(), "Toggle inlay hints")
    :map('n', "grd", kut.teleConfig("diagnostics", 'n'), "Telescope diagnostics")
    :map({ 'n', 'v' }, "<leader>md", "<Plug>VimspectorBalloonEval", "Evaluate statement in debugger")

M.color = kut.newMapGroup()
    :partial("n", "<leader>o", "colortoggle", "Toggle colorscheme")

M.oil = kut.newMapGroup()
    :gmap("n", "g?", "actions.open_external")
    :gmap("", "<CR>", "actions.select")
    :gmap("", "<leader>v", "actions.select", { vertical = true }, "vselect")
    :gmap("", "<leader>s", "actions.select", { horizontal = true }, "hselect")
    :gmap("", "<C-p>", "actions.preview")
    :gmap("", "<M-l>", "actions.refresh", nil, "refresh")
    :gmap("n", "<BS>", "actions.parent", nil, "parent")
    :gmap("n", "~", "actions.cd", nil, "cd")
    :gmap("n", "gs", "actions.change_sort")
    :gmap("", "gx", "actions.open_external")
    :gmap("", "gt", "actions.open_terminal", nil, "term")
    :gmap("", "<leader>nc", function() require "telescope-oil-columns".pick() end, nil, "cols")

M.gitsigns = kut.newMapGroup()
    :map('n', "<Leader>gb", function(gs) gs.blame_line() end, "Show git blame for current line")
    :map('n', "<Leader>gv", function(gs) gs.preview_hunk_inline() end, "Preview hunk under cursor")
    :map('n', "<Leader>gu", function(gs) gs.undo_stage_hunk() end, "Undo last hunk stage")
    :map('n', "<leader>gj", function(gs) gs.nav_hunk("last") end, "go to last hunk")
    :map('n', "<leader>gk", function(gs) gs.nav_hunk("first") end, "go to first hunk")
    :map('n', "<leader>j", function(gs) gs.nav_hunk("next") end, "go to next hunk")
    :map('n', "<leader>k", function(gs) gs.nav_hunk("prev") end, "go to previous hunk")

M.telescope_builtin = kut.newMapGroup()
    :map('n', "<leader>f", kut.teleConfig("builtin", 'n'), "List of telescope pickers")
    :map('n', "<leader>ff/", kut.teleConfig("current_buffer_fuzzy_find", 'i'), "Telescope find in file")
    :map('n', "<leader>ffr", kut.teleConfig("live_grep", 'i'), "Telescope search in all files")
    :map('n', "<leader>ffb", kut.teleConfig("buffers", 'n'), "Telescope list buffers")
    :map('n', "<leader>fff", kut.teleConfig("find_files", 'i'), "Telescope find file")
    :map('n', "<leader>fgv", kut.teleConfig("git_status", 'n'), "Telescope find file")
    :map('n', "<leader>fqq", kut.teleConfig("quickfixhistory", 'n'), "Telescope quickfix")
    :map('n', "<leader>fqf", kut.teleConfig("quickfix", 'n'), "Telescope quickfix")

M.telescope = kut.newMapGroup()
    :gmap({ "i", "n" }, "<c-b>", "preview_scrolling_down")
    :gmap({ "i", "n" }, "<c-f>", "preview_scrolling_up")
    :gmap("n", "v", "file_vsplit")
    :gmap("n", "t", "file_tab")
    :gmap("n", "ZZ", "close")

M.logical_lines = kut.newMapGroup()
    :map({ 'n', 'o' }, "j", "gj")
    :map({ 'n', 'o' }, "gj", "j")
    :map({ 'n', 'o' }, "k", "gk")
    :map({ 'n', 'o' }, "gk", "k")
    :map({ 'n', 'o' }, "0", "g0")
    :map({ 'n', 'o' }, "g0", "0")
    :map({ 'n', 'o' }, "^", "g^")
    :map({ 'n', 'o' }, "g^", "^")
    :map({ 'n', 'o' }, "$", "g$")
    :map({ 'n', 'o' }, "g$", "$")
    :map({ 'n', 'o' }, "D", "dg$")
    :map({ 'n', 'o' }, "C", "cg$")
    :map({ 'n', 'o' }, "A", "g$a")
    :map({ 'n', 'o' }, "I", "g^i")

M.quickfix = kut.newMapGroup()
    :map('n', ']q', qfix.inQfix(qfix.cnext), "next quickfix")
    :map('n', '[q', qfix.inQfix(qfix.cprev), "previous quickfix")

M.neorg = kut.newMapGroup()
    :map('n', "gO", "<cmd>Neorg toc<CR>", "Neorg TOC")
    :map('i', "<C-CR>", "<Plug>(neorg.itero.next-iteration)")

return M
